modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]] #mandatory
modId="wildlands" #mandatory
version="1.0.7" #mandatory
displayName="Wild Lands" #mandatory
credits="superlord9362 (code), weastian (assets), VakyPanda (assets)" #optional
authors="superlord9362" #optional

description='''Wild Lands is a vanilla-styled biome and wildlife mod, aiming to expand the vanilla world, as well as add to it. This ranges from adding new plants and animals to existing biomes, and adding fully fleshed out new biomes, such as the Bayou! The mod aims to feel very vanilla in what is added, with many interesting aspects and behaviors for many of the added animals!'''
[[dependencies.wildlands]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.wildlands]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

