modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]] #mandatory
modId="wildlands" #mandatory
version="1.1.0" #mandatory
displayName="Wild Lands" #mandatory
credits="superlord9362, weastiann, VakyPanda" #optional
authors="superlord9362" #optional

description='''${mod_description}'''
[[dependencies.wildlands]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.wildlands]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

